### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by tsn77130** [bharatraj88/logstash-filter-jwt-decode#1]
Hello, should it be possible to have some sample for plugin use please ? (fields name, syntax, ...)

Can't figure how to use it in logstash config.

**Comment by bharatraj88** [comment]
@tsn77130  You have the complete documentation with sample usages here 
https://github.com/bharatraj88/logstash-filter-jwt-decode/blob/master/docs/index.asciidoc

**Comment by tsn77130** [comment]
Hi @bharatraj88 , I've tried 

 filter {
  jwt_decode {
    "match" => "http.request.headers.x-token"
    "signature_alg" => "HS512"
    "extract_fields" => {"http.request.jwt.login" => "login"}
}
}

but i have error message
"[2020-01-09T09:58:55,358][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (PluginLoadingError) Couldn't find any filter plugin named 'jwt_decode'. Are you sure this is correct? Trying to load the jwt_decode filter plugin resulted in this error: no such file to load -- logstash/filters/jwt_decode"

with done before :
logstash-plugin install logstash-filter-jwt-decoder 
Validating logstash-filter-jwt-decoder
Installing logstash-filter-jwt-decoder
Installation successful

and plugin listed when using logstash-plugin list
Tried with docker version of logstash:7.5.1

Am I missing something ?
thanks
